Feat/link solucionador with tags
IncluiTech/incluitech-backend pull request #12
Opened 2020-05-20 04:00 UTC by jphrmartins

**DEPENDE DA BRANCH refact/saveSolucionadorFlow**

2020-05-20 12:17 UTC, alexiadorneles requested changes

2020-05-20 12:17 UTC, alexiadorneles commented on solucao-de-problemas-service/src/main/java/com/ages/incuitech/backend/solucaodeproblemasservice/business/cliente/ClienteService.java
> +                .map(cliente -> ClienteMapper.mapToResponseWithTags(cliente, findTags(cliente.getId())))
O ideal seria não fazermos request de select no banco dentro de loops, deve abrir muitas conexões. Seria legal se pudermos extrair isso pra um Map com id do Cliente e as Tags dele, de uma vez só, usando apenas o get() nesse loop

2020-05-20 12:17 UTC, alexiadorneles commented on solucao-de-problemas-service/src/main/java/com/ages/incuitech/backend/solucaodeproblemasservice/business/solucionador/SolucionadorService.java
> +                .map(solucionador -> SolucionadorMapper.mapToResponseWithTags(solucionador, buscarTags(solucionador.getId())))
Mesma coisa que comentei do cliente.

2020-05-20 12:17 UTC, alexiadorneles commented on solucao-de-problemas-service/src/main/java/com/ages/incuitech/backend/solucaodeproblemasservice/business/solucionador/SolucionadorService.java
> +                TagSolucionador.builder()
Isso não parece que deveria estar aqui... Acho que o correto seria ter o serviço de tag com essa responsabilidade, mas como estamos usando o repository direto podia ter um método num TagMapper ou algo assim pra criar esse objeto de forma isolada.

2020-05-20 12:17 UTC, alexiadorneles commented on solucao-de-problemas-service/src/main/java/com/ages/incuitech/backend/solucaodeproblemasservice/business/solucionador/SolucionadorService.java
> +        ).collect(Collectors.toList()));
Sugestão: import static 
É só sugestão mesmo, porque acho que fica mais bonitinho. Mas se discordarem não vejo problema em ficar assim hehehe

2020-05-20 12:17 UTC, alexiadorneles commented on solucao-de-problemas-service/src/main/java/com/ages/incuitech/backend/solucaodeproblemasservice/business/tag/TagMapper.java
> +public class TagMapper {
Acho boa fazer construtores privados nos mappers pra deixar explicito que nunca este pattern deve ser usado como instancia

2020-05-20 12:17 UTC, CarlosAsrc approved these changes

2020-05-20 12:23 UTC, CarlosAsrc reviewed
Achei bem pertinente os comentários da @alexiadorneles, após a avaliação dessas mudanças por mim ta OK pra mergear.

2020-05-21 02:38 UTC, alexiadorneles commented on solucao-de-problemas-service/src/main/java/com/ages/incuitech/backend/solucaodeproblemasservice/business/solucionador/SolucionadorService.java
> +                TagSolucionador.builder()
@jphrmartins essa aqui chegou a ser comentada?

2020-05-21 13:48 UTC, jphrmartins commented on solucao-de-problemas-service/src/main/java/com/ages/incuitech/backend/solucaodeproblemasservice/business/tag/TagMapper.java
> +public class TagMapper {
não vejo muita necessidade pq todos os metodos já são estaticos, então n vai adiante de muito ter como dependencia de uma outra classe algo que tu só chama pelo nome

2020-05-21 14:01 UTC, alexiadorneles commented on solucao-de-problemas-service/src/main/java/com/ages/incuitech/backend/solucaodeproblemasservice/business/tag/TagMapper.java
> +public class TagMapper {
Eu vejo várias práticas ótimas da programação que vão além da necessidade básica do código rs

2020-05-21 14:02 UTC, alexiadorneles approved these changes

2020-05-21 15:09 UTC, merged